DROP TABLE IF EXISTS 
    People , 
    Roles,
    Person_Role,
    Subject_Offer,
    Category_Tags,
    Filters,
    Person_Filter_Access,
    Sop_Form, 
    Course,
    Teaching_Assigment,
    People_Group,
    Program,
    Subjects,
CASCADE;
