name: C++ CI

on:
  push:
    branches:
      - '**'

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang-tidy clang-format cppcheck libboost-all-dev libssl-dev

      - name: Cache tgbot-cpp
        id: cache-tgbot
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/libTgBot.so
          key: tgbot-${{ runner.os }}-v1

      - name: Build tgbot-cpp
        if: steps.cache-tgbot.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/reo7sp/tgbot-cpp.git
          cd tgbot-cpp
          mkdir build && cd build
          cmake ..
          make -j$(nproc)
          sudo make install

      - name: Run clang-tidy (only changed files)
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD | grep -E '\.(cpp|h)$' || echo "")
          if [[ -n "$CHANGED_FILES" ]]; then
            clang-tidy $CHANGED_FILES -- -I./include || true
          else
            echo "No C++ files changed."
          fi

      - name: Run clang-format (only changed files)
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD | grep -E '\.(cpp|h)$' || echo "")
          if [[ -n "$CHANGED_FILES" ]]; then
            clang-format -i $CHANGED_FILES || true
          else
            echo "No C++ files changed."
          fi

      - name: Run cppcheck
        run: cppcheck --enable=all --inconclusive --quiet --std=c++17 --suppress=missingIncludeSystem .
