name: Static Analysis Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

defaults:
  run:
    working-directory: .

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON


  clang-tidy:
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore Cached Build
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Run Clang Tidy
        run: |
          clang-tidy source/*.cpp include/*.hpp


        
