name: Clang Checks

on:
  pull_request:
    branches:
      - dev/meytardzhevtd  

defaults:
  run:
    working-directory: .  

jobs:
  clang-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Clang tools
        run: sudo apt-get install -y clang-format clang-tidy

      - name: Run Clang Format
        run: |
          find include source -name '*.cpp' -o -name '*.h' | xargs clang-format -i
          git diff --exit-code || (echo "Clang format check failed! Run clang-format and commit changes."; exit 1)

      - name: Run Clang Tidy
        run: |
          find source -name '*.cpp' | xargs clang-tidy --warnings-as-errors=*
