name: Clang Checks
on:
  push:
    branches:
      - '**'
defaults:
  run:
    working-directory: ..
jobs:
  c:
    uses: ./.github/workflows/clang-checks.yml
    with:
      working_directory: ..
      simple_compilation_name: my_bot
