name: Clang Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run Clang Format
        run: |
          find include source -name '*.cpp' -o -name '*.hpp' | xargs clang-format -i
          git diff --exit-code || (echo "Clang format check failed! Run clang-format and commit changes."; exit 1)

