name: Clang Format Check

on:
  push:
    branches:
      - '**'

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Clang Format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Run Clang Format
        run: |
          CHANGED_FILES=$(git ls-files '*.cpp' '*.h')
          if [[ -n "$CHANGED_FILES" ]]; then
            echo "$CHANGED_FILES" | xargs clang-format -i
            git diff --exit-code || (echo "Clang format check failed! Run clang-format and commit changes."; exit 1)
          else
            echo "No C++ files found."
          fi
