name: CppCheck Analysis

on:
  push:
    branches:
      - '**'

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck libboost-all-dev libssl-dev

      - name: Cache TgBot
        id: cache-tgbot
        uses: actions/cache@v3
        with:
          path: |
            /usr/local/lib/libTgBot.so
            /usr/local/include/tgbot
          key: tgbot-${{ runner.os }}-v1

      - name: Install TgBot
        if: steps.cache-tgbot.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/reo7sp/tgbot-cpp.git
          cd tgbot-cpp
          mkdir build && cd build
          cmake ..
          make -j$(nproc)
          sudo make install

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DTgBot_DIR=/usr/local/lib/cmake/TgBot

      - name: Cache CppCheck results
        uses: actions/cache@v3
        with:
          path: .cppcheck_cache
          key: cppcheck-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            cppcheck-${{ runner.os }}-

      - name: Run CppCheck
        run: |
          mkdir -p .cppcheck_cache
          cppcheck --enable=all --inconclusive --quiet --error-exitcode=1 \
                   --project=build/compile_commands.json \
                   --cppcheck-build-dir=.cppcheck_cache \
                   source include
