name: CppCheck Analysis

on:
  push:
    branches:
      - '**'

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run CppCheck
        run: |
          cppcheck --enable=all --inconclusive --quiet --error-exitcode=1 --project=build/compile_commands.json --suppress=build/*
