name: Install Dependencies

on:
  workflow_call:

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format clang-tidy libboost-all-dev \
                                  libcurl4-openssl-dev libpq-dev \
                                  nlohmann-json3-dev libpqxx-dev